### ISSUE TITLE
Can't install 1.3.0 through pypi

### ISSUE THREAD

**Issue by syabro** [nivbend/mock-open#5]
Looks like 1.3.0 pypi version missing a download file
https://pypi.python.org/pypi/mock-open/1.3.0

So I can't install it 

![](http://s.syabro.com/efpsq.png)

**Comment by nivbend** [comment]
Please use v1.3.1 instead. There are no functional differences between the versions.

**Comment by syabro** [comment]
@nivbend thanks!
